name: nakshatra_vatika
description: Raj Bhawan Dehradun - Nakshatra Vatika

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  webview_flutter_plus: ^0.3.0+2
  fluttertoast: ^8.2.2
  getwidget: ^4.0.0
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/circleNV.PNG
    - assets/sideElementNV.png
    - assets/loader.gif
  fonts:
    - family: TiltNeon
      fonts:
        - asset: assets/fonts/TiltNeon-Regular.ttf